// generated by scripts/gen-embed.ts — do not commit a non-empty version
import f0 from "../../web/dist/index.html" with { type: "file" };
import f1 from "../../web/dist/assets/or-50rxpoq4-B_XNinj_.js" with { type: "file" };
import f2 from "../../web/dist/assets/bn-NCLZcWHi-CsgykzQM.js" with { type: "file" };
import f3 from "../../web/dist/assets/hsb-DC_ITc1e-C4pa9vvS.js" with { type: "file" };
import f4 from "../../web/dist/assets/el-polyton-ogVWcTzh-BOWLBXgh.js" with { type: "file" };
import f5 from "../../web/dist/assets/da-CCDXfXtG-C3O8h2wc.js" with { type: "file" };
import f6 from "../../web/dist/assets/rm-C0MIK9N4-DeBfDBrx.js" with { type: "file" };
import f7 from "../../web/dist/assets/lv-Q2BBHnzp-DRPSUjhQ.js" with { type: "file" };
import f8 from "../../web/dist/assets/SqlField-CwGayAzf.js" with { type: "file" };
import f9 from "../../web/dist/assets/fi-RW5VB8Yp-C_52fTOR.js" with { type: "file" };
import f10 from "../../web/dist/assets/cs-CmAteokq-TjIVgNl6.js" with { type: "file" };
import f11 from "../../web/dist/assets/de-ch-1901-hVThVHVb-CC5Yf8hX.js" with { type: "file" };
import f12 from "../../web/dist/assets/de-1901-CWoAOigE-yOXirf_M.js" with { type: "file" };
import f13 from "../../web/dist/assets/mn-cyrl-lHM4n0oC-QhYuXAWB.js" with { type: "file" };
import f14 from "../../web/dist/assets/mn-cyrl-x-lmc-3aetruI8-mEBV16An.js" with { type: "file" };
import f15 from "../../web/dist/assets/fr-BC2onEz9-BGmqATrI.js" with { type: "file" };
import f16 from "../../web/dist/assets/nb-DI8u59ch-S2a9vUN_.js" with { type: "file" };
import f17 from "../../web/dist/assets/tr-CIHIuzqc-ZkOY1dVp.js" with { type: "file" };
import f18 from "../../web/dist/assets/ca-SUf6Y2Om-Dp4lcbPL.js" with { type: "file" };
import f19 from "../../web/dist/assets/be-CrQ0smca-B2EeXxUh.js" with { type: "file" };
import f20 from "../../web/dist/assets/uk-Dir3oxLs-BVEQM3Jf.js" with { type: "file" };
import f21 from "../../web/dist/assets/Workbench-xeQVRSRZ.css" with { type: "file" };
import f22 from "../../web/dist/assets/cy-BBPa6z2x-BONU7bVJ.js" with { type: "file" };
import f23 from "../../web/dist/assets/hu-DVk7Y_ka-CCTZJfqn.js" with { type: "file" };
import f24 from "../../web/dist/assets/hy-e995ysyO-Cf-NYmW5.js" with { type: "file" };
import f25 from "../../web/dist/assets/pi-B9cgjyG1-v-IB86gp.js" with { type: "file" };
import f26 from "../../web/dist/assets/la-DuvHjUWw-BcBNkSEh.js" with { type: "file" };
import f27 from "../../web/dist/assets/oc-P_i3-xLA-Cg0Gj-PC.js" with { type: "file" };
import f28 from "../../web/dist/assets/Workbench-DjPIMZsX.js" with { type: "file" };
import f29 from "../../web/dist/assets/et-B_spaleu-BaO20FM2.js" with { type: "file" };
import f30 from "../../web/dist/assets/bg-CrQqGwni-Pt9yPLke.js" with { type: "file" };
import f31 from "../../web/dist/assets/te-B5Spl2Jk-DYnT8Dmf.js" with { type: "file" };
import f32 from "../../web/dist/assets/as-BPtSu6VN-CYxxmKqh.js" with { type: "file" };
import f33 from "../../web/dist/assets/lt-BBe8DlDF-CObMPDIF.js" with { type: "file" };
import f34 from "../../web/dist/assets/it-Bt_Meacx-BwawXXgW.js" with { type: "file" };
import f35 from "../../web/dist/assets/la-x-classic-yTyAOQEt-DuDJBVty.js" with { type: "file" };
import f36 from "../../web/dist/assets/af-DK_CjRn6-C81U6qP1.js" with { type: "file" };
import f37 from "../../web/dist/assets/en-gb-B7Al27b_-BFFr9zKP.js" with { type: "file" };
import f38 from "../../web/dist/assets/CredentialsPanel-DUYlCPlN.js" with { type: "file" };
import f39 from "../../web/dist/assets/Editor-Cn2G7kMa.js" with { type: "file" };
import f40 from "../../web/dist/assets/sl-DpiklF-D-_46w5B9b.js" with { type: "file" };
import f41 from "../../web/dist/assets/de-1996-BL6awyxG-BSuIomZy.js" with { type: "file" };
import f42 from "../../web/dist/assets/gu-Bjl0l-cf-Bb_OSiMJ.js" with { type: "file" };
import f43 from "../../web/dist/assets/gl-DZGc-K_G-DLl5jmsP.js" with { type: "file" };
import f44 from "../../web/dist/assets/Login-Dr62-IXn.js" with { type: "file" };
import f45 from "../../web/dist/assets/kn-C6Lov-DP-D7dHjlY1.js" with { type: "file" };
import f46 from "../../web/dist/assets/Reports-BxFnMQOt.js" with { type: "file" };
import f47 from "../../web/dist/assets/grc-DOlGgO8T-C7K_Bcib.js" with { type: "file" };
import f48 from "../../web/dist/assets/no-B8ItS0F3-BlrHaK3Z.js" with { type: "file" };
import f49 from "../../web/dist/assets/ia-Cr4TJH0c-BcFKNbxH.js" with { type: "file" };
import f50 from "../../web/dist/assets/nl-BHQJ6Gvn-BMWl-SdQ.js" with { type: "file" };
import f51 from "../../web/dist/assets/sv-CFm5y56M-I8ncZ9Nb.js" with { type: "file" };
import f52 from "../../web/dist/assets/kmr-Cfwhwuff-DNWs8Gbk.js" with { type: "file" };
import f53 from "../../web/dist/assets/mr-CjWJPVmH-BKMRnoAc.js" with { type: "file" };
import f54 from "../../web/dist/assets/th-DWX5iPSo-BI_G36o8.js" with { type: "file" };
import f55 from "../../web/dist/assets/la-x-liturgic-CXeQb4FY-DNU_Uk5t.js" with { type: "file" };
import f56 from "../../web/dist/assets/fur-AC12wySk-Ulg0Fy5V.js" with { type: "file" };
import f57 from "../../web/dist/assets/sh-latn-sRy4Tuaj-DcyoDtEt.js" with { type: "file" };
import f58 from "../../web/dist/assets/cop-C3sk0IUo-Cj8cOj0I.js" with { type: "file" };
import f59 from "../../web/dist/assets/ChartHost-CRwmXR4r.js" with { type: "file" };
import f60 from "../../web/dist/assets/zh-latn-pinyin-BdYb-Ey_-BpSBSv6m.js" with { type: "file" };
import f61 from "../../web/dist/assets/nn-ntZvarUK-cMBifkqM.js" with { type: "file" };
import f62 from "../../web/dist/assets/tk-BMbKB10q-cqtw6prh.js" with { type: "file" };
import f63 from "../../web/dist/assets/pl-9fg-ESVt-DpPW5ISU.js" with { type: "file" };
import f64 from "../../web/dist/assets/hi-DsAaTPCC-lc1bUHMk.js" with { type: "file" };
import f65 from "../../web/dist/assets/sr-cyrl-Dpzrbd0W-DKfS_grW.js" with { type: "file" };
import f66 from "../../web/dist/assets/Explorer-BVJUEnuC.js" with { type: "file" };
import f67 from "../../web/dist/assets/pt-Cum2_NUC-D8aZaPM_.js" with { type: "file" };
import f68 from "../../web/dist/assets/id-DifDyWg9-1QUBE4o0.js" with { type: "file" };
import f69 from "../../web/dist/assets/is-BT8UVRze-BXloJ18M.js" with { type: "file" };
import f70 from "../../web/dist/assets/ro-0fmdH0HA-1lLksn9e.js" with { type: "file" };
import f71 from "../../web/dist/assets/es-DcaaHPU_-sYKznHcq.js" with { type: "file" };
import f72 from "../../web/dist/assets/el-monoton-D3aKqTz2-DpMW17GV.js" with { type: "file" };
import f73 from "../../web/dist/assets/ta-BcghgTbD-D3SGVeDl.js" with { type: "file" };
import f74 from "../../web/dist/assets/hr-DT1SBBes-CkK3TemH.js" with { type: "file" };
import f75 from "../../web/dist/assets/cu-CBUlrW6Y-BrxB2kb-.js" with { type: "file" };
import f76 from "../../web/dist/assets/ga-Cn6LkudM-WsF4_z3Y.js" with { type: "file" };
import f77 from "../../web/dist/assets/sk-_iOeDNrQ-BXQc18Za.js" with { type: "file" };
import f78 from "../../web/dist/assets/index-DRXVRTKV.css" with { type: "file" };
import f79 from "../../web/dist/assets/index-CewIfKSX.js" with { type: "file" };
import f80 from "../../web/dist/assets/pms-BRGfm5gS-DtZRgBhp.js" with { type: "file" };
import f81 from "../../web/dist/assets/eu-Ctv_kq9Z-DMhU9kwg.js" with { type: "file" };
import f82 from "../../web/dist/assets/ru-v4l-ayaq-BZkHNr9F.js" with { type: "file" };
import f83 from "../../web/dist/assets/api-BuO9Skjo.js" with { type: "file" };
import f84 from "../../web/dist/assets/ml-2xLVYkVY-CBhOFsDv.js" with { type: "file" };
import f85 from "../../web/dist/assets/objectWithoutPropertiesLoose-Cv5OCJ0e.js" with { type: "file" };
import f86 from "../../web/dist/assets/ka-jyoLzyDE-CZftRBZr.js" with { type: "file" };
import f87 from "../../web/dist/assets/Preview-Dr2cDOw2.js" with { type: "file" };
import f88 from "../../web/dist/assets/sh-cyrl-BpCRFOmq-Cv4-R-p6.js" with { type: "file" };
import f89 from "../../web/dist/assets/sa-CKY9c_Vq-DzgpFnfw.js" with { type: "file" };
import f90 from "../../web/dist/assets/pa-C54UG8eN-EW_8hrTF.js" with { type: "file" };
import f91 from "../../web/dist/assets/mul-ethi-D_CMSMEq-2TGBnG-Z.js" with { type: "file" };

export const embedded: Record<string, string> = {
  "/index.html": f0,
  "/assets/or-50rxpoq4-B_XNinj_.js": f1,
  "/assets/bn-NCLZcWHi-CsgykzQM.js": f2,
  "/assets/hsb-DC_ITc1e-C4pa9vvS.js": f3,
  "/assets/el-polyton-ogVWcTzh-BOWLBXgh.js": f4,
  "/assets/da-CCDXfXtG-C3O8h2wc.js": f5,
  "/assets/rm-C0MIK9N4-DeBfDBrx.js": f6,
  "/assets/lv-Q2BBHnzp-DRPSUjhQ.js": f7,
  "/assets/SqlField-CwGayAzf.js": f8,
  "/assets/fi-RW5VB8Yp-C_52fTOR.js": f9,
  "/assets/cs-CmAteokq-TjIVgNl6.js": f10,
  "/assets/de-ch-1901-hVThVHVb-CC5Yf8hX.js": f11,
  "/assets/de-1901-CWoAOigE-yOXirf_M.js": f12,
  "/assets/mn-cyrl-lHM4n0oC-QhYuXAWB.js": f13,
  "/assets/mn-cyrl-x-lmc-3aetruI8-mEBV16An.js": f14,
  "/assets/fr-BC2onEz9-BGmqATrI.js": f15,
  "/assets/nb-DI8u59ch-S2a9vUN_.js": f16,
  "/assets/tr-CIHIuzqc-ZkOY1dVp.js": f17,
  "/assets/ca-SUf6Y2Om-Dp4lcbPL.js": f18,
  "/assets/be-CrQ0smca-B2EeXxUh.js": f19,
  "/assets/uk-Dir3oxLs-BVEQM3Jf.js": f20,
  "/assets/Workbench-xeQVRSRZ.css": f21,
  "/assets/cy-BBPa6z2x-BONU7bVJ.js": f22,
  "/assets/hu-DVk7Y_ka-CCTZJfqn.js": f23,
  "/assets/hy-e995ysyO-Cf-NYmW5.js": f24,
  "/assets/pi-B9cgjyG1-v-IB86gp.js": f25,
  "/assets/la-DuvHjUWw-BcBNkSEh.js": f26,
  "/assets/oc-P_i3-xLA-Cg0Gj-PC.js": f27,
  "/assets/Workbench-DjPIMZsX.js": f28,
  "/assets/et-B_spaleu-BaO20FM2.js": f29,
  "/assets/bg-CrQqGwni-Pt9yPLke.js": f30,
  "/assets/te-B5Spl2Jk-DYnT8Dmf.js": f31,
  "/assets/as-BPtSu6VN-CYxxmKqh.js": f32,
  "/assets/lt-BBe8DlDF-CObMPDIF.js": f33,
  "/assets/it-Bt_Meacx-BwawXXgW.js": f34,
  "/assets/la-x-classic-yTyAOQEt-DuDJBVty.js": f35,
  "/assets/af-DK_CjRn6-C81U6qP1.js": f36,
  "/assets/en-gb-B7Al27b_-BFFr9zKP.js": f37,
  "/assets/CredentialsPanel-DUYlCPlN.js": f38,
  "/assets/Editor-Cn2G7kMa.js": f39,
  "/assets/sl-DpiklF-D-_46w5B9b.js": f40,
  "/assets/de-1996-BL6awyxG-BSuIomZy.js": f41,
  "/assets/gu-Bjl0l-cf-Bb_OSiMJ.js": f42,
  "/assets/gl-DZGc-K_G-DLl5jmsP.js": f43,
  "/assets/Login-Dr62-IXn.js": f44,
  "/assets/kn-C6Lov-DP-D7dHjlY1.js": f45,
  "/assets/Reports-BxFnMQOt.js": f46,
  "/assets/grc-DOlGgO8T-C7K_Bcib.js": f47,
  "/assets/no-B8ItS0F3-BlrHaK3Z.js": f48,
  "/assets/ia-Cr4TJH0c-BcFKNbxH.js": f49,
  "/assets/nl-BHQJ6Gvn-BMWl-SdQ.js": f50,
  "/assets/sv-CFm5y56M-I8ncZ9Nb.js": f51,
  "/assets/kmr-Cfwhwuff-DNWs8Gbk.js": f52,
  "/assets/mr-CjWJPVmH-BKMRnoAc.js": f53,
  "/assets/th-DWX5iPSo-BI_G36o8.js": f54,
  "/assets/la-x-liturgic-CXeQb4FY-DNU_Uk5t.js": f55,
  "/assets/fur-AC12wySk-Ulg0Fy5V.js": f56,
  "/assets/sh-latn-sRy4Tuaj-DcyoDtEt.js": f57,
  "/assets/cop-C3sk0IUo-Cj8cOj0I.js": f58,
  "/assets/ChartHost-CRwmXR4r.js": f59,
  "/assets/zh-latn-pinyin-BdYb-Ey_-BpSBSv6m.js": f60,
  "/assets/nn-ntZvarUK-cMBifkqM.js": f61,
  "/assets/tk-BMbKB10q-cqtw6prh.js": f62,
  "/assets/pl-9fg-ESVt-DpPW5ISU.js": f63,
  "/assets/hi-DsAaTPCC-lc1bUHMk.js": f64,
  "/assets/sr-cyrl-Dpzrbd0W-DKfS_grW.js": f65,
  "/assets/Explorer-BVJUEnuC.js": f66,
  "/assets/pt-Cum2_NUC-D8aZaPM_.js": f67,
  "/assets/id-DifDyWg9-1QUBE4o0.js": f68,
  "/assets/is-BT8UVRze-BXloJ18M.js": f69,
  "/assets/ro-0fmdH0HA-1lLksn9e.js": f70,
  "/assets/es-DcaaHPU_-sYKznHcq.js": f71,
  "/assets/el-monoton-D3aKqTz2-DpMW17GV.js": f72,
  "/assets/ta-BcghgTbD-D3SGVeDl.js": f73,
  "/assets/hr-DT1SBBes-CkK3TemH.js": f74,
  "/assets/cu-CBUlrW6Y-BrxB2kb-.js": f75,
  "/assets/ga-Cn6LkudM-WsF4_z3Y.js": f76,
  "/assets/sk-_iOeDNrQ-BXQc18Za.js": f77,
  "/assets/index-DRXVRTKV.css": f78,
  "/assets/index-CewIfKSX.js": f79,
  "/assets/pms-BRGfm5gS-DtZRgBhp.js": f80,
  "/assets/eu-Ctv_kq9Z-DMhU9kwg.js": f81,
  "/assets/ru-v4l-ayaq-BZkHNr9F.js": f82,
  "/assets/api-BuO9Skjo.js": f83,
  "/assets/ml-2xLVYkVY-CBhOFsDv.js": f84,
  "/assets/objectWithoutPropertiesLoose-Cv5OCJ0e.js": f85,
  "/assets/ka-jyoLzyDE-CZftRBZr.js": f86,
  "/assets/Preview-Dr2cDOw2.js": f87,
  "/assets/sh-cyrl-BpCRFOmq-Cv4-R-p6.js": f88,
  "/assets/sa-CKY9c_Vq-DzgpFnfw.js": f89,
  "/assets/pa-C54UG8eN-EW_8hrTF.js": f90,
  "/assets/mul-ethi-D_CMSMEq-2TGBnG-Z.js": f91,
};
