// scripts/gen-embed.ts — run from repo root by `make generate`.
// Walks the built UI (apps/web/dist) and rewrites apps/server/src/embedded.ts with a
// `with { type: "file" }` import per asset. Those imports are what `bun build --compile`
// packs into the binary; `make package` restores the empty committed default afterwards,
// so a non-empty embedded.ts must never be committed (tsc/biome never see these lines).
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const dist = "apps/web/dist";
const files: string[] = [];
(function walk(dir: string) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
})(dist);

const imports = files.map(
  (p, i) => `import f${i} from "../../web/dist/${relative(dist, p)}" with { type: "file" };`,
);
const entries = files.map((p, i) => `  "/${relative(dist, p)}": f${i},`);
writeFileSync(
  "apps/server/src/embedded.ts",
  `// generated by scripts/gen-embed.ts — do not commit a non-empty version\n${imports.join("\n")}\n\nexport const embedded: Record<string, string> = {\n${entries.join("\n")}\n};\n`,
);
console.log(`embedded ${files.length} files`);
